import { Arimo } from "next/font/google";
import { AuthContextProvider } from "./auth/Provider";
import GoogleAnalyticsScript from "./components/GoogleAnalyticsScript";
import HydrationZustand from "./components/HydrationZustand";
import ImageForPages from "./components/ImageForPages";
import Navbar2 from "./components/Navbar/Navbar2";
import "./globals.css";

const inter = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Nutura | Sprejové vitamíny",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sk">
      <GoogleAnalyticsScript />
      <body className={inter.className}>
        <AuthContextProvider>
          <HydrationZustand>
            <ImageForPages />
            <Navbar2 />
            {children}
          </HydrationZustand>
        </AuthContextProvider>
      </body>
    </html>
  );
}
